version = 1

[[annotations]]
path = [
  ".envrc",
  ".gitignore",
  "Cargo.lock",
  "deny.toml",
  "flake.lock",
  "renovate.json",
  "THIRD_PARTY"
]
SPDX-FileCopyrightText = "NONE"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
  "command_line_help.md"
]
SPDX-FileCopyrightText = "Mathias Polligkeit"
SPDX-License-Identifier = "AGPL-3.0-or-later"
