# SPDX-FileCopyrightText: NONE
#
# SPDX-License-Identifier: CC0-1.0

name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5.1.0
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - name: Check Format
        run: cargo fmt --all --check
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features --no-deps
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cargo test --verbose
